# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMKVPfS2OdRmyOEh-qvnGWhTZ54rUz0K
"""

import numpy as np
import pandas as pd

#string

country=['nepal','india','pakistan']
pd.Series(country)

#integer

numbers=[70,80,90,]
pd.Series(numbers)

#custom index

numbers=[70,80,90,]
subjects=['maths','science','english']
pd.Series(numbers,index=subjects)

#setting a name

marks=pd.Series(numbers,index=subjects,name='marks')
marks

#series from dict
marks={
    'maths':67,
    'science':80
}
marks_series=pd.Series(marks,name='Marks')
marks_series

"""Series Attributes"""

#size
marks_series.size

#dtype
marks_series.dtype

#name
marks_series.name

#is_unique
marks_series.is_unique

#index
marks_series.index

#values
marks_series.values

"""Series using read_csv

"""

#with one col
df = pd.read_csv('/content/subs.csv')

series = df.squeeze("columns")
series

#with two col

#with one col
df = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no')

series = df.squeeze("columns")
series



#with one col
df = pd.read_csv('/content/bollywood.csv',index_col='movie')

series = df.squeeze("columns")
series